dist: trusty
language: go
go:
  - 1.12.7
env:
  global:
    - CGO_ENABLED=1
    - GO111MODULE=on
gobuild_args: -a -tags netgo -ldflags "-w -X main.version=${TRAVIS_COMMIT}"
go_import_path: github.com/adevinta/vulcan-agent
before_script:
  - wget -O dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
  - chmod +x ./dep
  - ./dep ensure -v
script:
  - go test -short -race -v $(go list ./... | grep -v /vendor/)
