language: go
go:
  - 1.15
env:
  global:
    - CGO_ENABLED=1
gobuild_args: -a -tags netgo -ldflags "-w -X main.version=${TRAVIS_COMMIT}"
go_import_path: github.com/adevinta/vulcan-agent
install: _script/bootstrap
script: _script/cibuild
