dist: trusty
language: go
services:
  - docker
go:
  - 1.13.3
env:
  global:
    - CGO_ENABLED=1
    - GO111MODULE=on
gobuild_args: -a -tags netgo -ldflags "-w -X main.version=${TRAVIS_COMMIT}"
go_import_path: github.com/adevinta/vulcan-agent
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - go test -short -race -v $(go list ./... | grep -v /vendor/)
