[agent]
jobqueue_id = "$JOBQUEUE_ID"
log_level = "$LOG_LEVEL"
log_file = ""
timeout = 300

[scheduler]
concurrent_jobs = 10
monitor_interval = 1
heartbeat_interval = 10

[persistence]
endpoint = "$PERSISTENCE_ENDPOINT"
timeout = 3
retries = 3

[uploader]
endpoint = "$RESULTS_ENDPOINT"
timeout = 10

[stream]
endpoint = "$STREAM_ENDPOINT"
timeout = 60

[sqs]
polling_interval = 5

[api]
port = ":$PORT"

[check]
abort_timeout = 60
log_level = "$CHECK_LOG_LEVEL"

[check.vars]
NESSUS_ENDPOINT = "$NESSUS_ENDPOINT"
NESSUS_USERNAME = "$NESSUS_USERNAME"
NESSUS_PASSWORD = "$NESSUS_PASSWORD"
GITHUB_ENTERPRISE_TOKEN = "$GITHUB_ENTERPRISE_TOKEN"

[runtime]
[runtime.docker]
[runtime.docker.registry]

[runtime.kubernetes]
[runtime.kubernetes.cluster]

[runtime.gateway]
endpoint = "$GATEWAY_ENDPOINT"

[asg]
interval = 300
region = "eu-west-1"
state_file = "/tmp/vulcan-agent-autoscaling.dat"

[datadog]
dogstatsd = "127.0.0.1:8125"
