[[constraint]]
  name = "github.com/docker/docker"
  revision = "092cba3727bb9b4a2f0e922cd6c0f93ea270e363"
  source = "https://github.com/moby/moby.git"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "v1.0.6"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
    version = "v1.1"

[[constraint]]
  name = "github.com/BurntSushi/toml"
    version = "v0.3.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.15.24"

[[constraint]]
  name = "github.com/lestrrat-go/backoff"
  revision = "828830ec1d9a363a7891cc6924f1acbebc62ecce"

[[constraint]]
  name = "github.com/adevinta/dockerutils"
  branch = "master"

[[constraint]]
  name = "github.com/adevinta/vulcan-report"
  branch = "master"
